from flask import Flask, render_template, jsonify, request

# Initialize the Flask application
app = Flask(__name__)

# --- Mock API Database ---
# This data is moved from the frontend to the backend.
mock_api_database = [
    { "data": { "client_id": "mobile_to_prefill_v3_ScLOIHCrrmxZAqBQNStN", "mobile_number": "7827234123", "prefill_details": { "client_id": "prefill_report_v2_ScLOIHCrrmxZAqBQNStN", "name": "SATEESH SINGH", "mobile": "7827234123", "personal_info": { "full_name": "SATEESH SINGH", "dob": "1994-11-02", "gender": "Male", "total_income": "30000", "occupation": "None", "age": "30" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "7827234123" } ], "address_info": [ { "address": "MURHARIA KAIMUR BHABU", "state": "BR", "type": "Owns,Permanent", "postal": "921102", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "SATEESH123@GMAIL.COM" } ], "identity_info": { "pan_number": [ { "id_number": "FYWPS1234M" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "FYWPS1234M", "full_name": "SATEESH SINGH", "full_name_split": [ "SATEESH", "SINGH" ], "masked_aadhaar": "XXXXXXXX2902", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "M", "dob": "1994-11-02", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_ArjunSample", "mobile_number": "9884092693", "prefill_details": { "client_id": "prefill_report_v2_ArjunSample", "name": "ARJUN SINGH", "mobile": "9884092693", "personal_info": { "full_name": "ARJUN SINGH", "dob": "1988-07-20", "gender": "Male", "total_income": "60000", "occupation": "Engineer", "age": "36" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "9884092693" } ], "address_info": [ { "address": "45, GANDHI NAGAR, CHENNAI", "state": "TN", "type": "Owns,Permanent", "postal": "600020", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "ARJUN.S@EXAMPLE.COM" } ], "identity_info": { "pan_number": [ { "id_number": "ABCDE1234F" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "ABCDE1234F", "full_name": "ARJUN SINGH", "full_name_split": [ "ARJUN", "SINGH" ], "masked_aadhaar": "XXXXXXXX1234", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "M", "dob": "1988-07-20", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample04", "mobile_number": "7890123456", "prefill_details": { "client_id": "prefill_report_v2_Sample04", "name": "RAHUL GUPTA", "mobile": "7890123456", "personal_info": { "full_name": "RAHUL GUPTA", "dob": "1975-09-22", "gender": "Male", "total_income": "80000", "occupation": "Businessman", "age": "49" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "7890123456" } ], "address_info": [ { "address": "B-10, SECTOR 18, GURUGRAM", "state": "HR", "type": "Owns,Permanent", "postal": "122008", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "RAHUL.G@BUSINESS.COM" } ], "identity_info": { "pan_number": [ { "id_number": "LMNOQ9012R" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "LMNOQ9012R", "full_name": "RAHUL GUPTA", "full_name_split": [ "RAHUL", "GUPTA" ], "masked_aadhaar": "XXXXXXXX9012", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "M", "dob": "1975-09-22", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample05", "mobile_number": "9988776655", "prefill_details": { "client_id": "prefill_report_v2_Sample05", "name": "SWAPNA REDDY", "mobile": "9988776655", "personal_info": { "full_name": "SWAPNA REDDY", "dob": "1992-11-05", "gender": "Female", "total_income": "55000", "occupation": "Software Developer", "age": "32" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "9988776655" } ], "address_info": [ { "address": "FLAT 301, CYBER TOWERS, HYDERABAD", "state": "TS", "type": "Owns,Permanent", "postal": "500081", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "SWAPNA.R@TECH.IN" } ], "identity_info": { "pan_number": [ { "id_number": "PQRST3456U" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "PQRST3456U", "full_name": "SWAPNA REDDY", "full_name_split": [ "SWAPNA", "REDDY" ], "masked_aadhaar": "XXXXXXXX3456", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "F", "dob": "1992-11-05", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample06", "mobile_number": "8765432109", "prefill_details": { "client_id": "prefill_report_v2_Sample06", "name": "AMIT KUMAR", "mobile": "8765432109", "personal_info": { "full_name": "AMIT KUMAR", "dob": "1980-01-25", "gender": "Male", "total_income": "70000", "occupation": "Doctor", "age": "45" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "8765432109" } ], "address_info": [ { "address": "15, HOSPITAL ROAD, BANGALORE", "state": "KA", "type": "Owns,Permanent", "postal": "560001", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "AMIT.K@MED.IN" } ], "identity_info": { "pan_number": [ { "id_number": "VWXYZ7890A" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "VWXYZ7890A", "full_name": "AMIT KUMAR", "full_name_split": [ "AMIT", "KUMAR" ], "masked_aadhaar": "XXXXXXXX7890", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "M", "dob": "1980-01-25", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample07", "mobile_number": "7778889990", "prefill_details": { "client_id": "prefill_report_v2_Sample07", "name": "NIDHI SHARMA", "mobile": "7778889990", "personal_info": { "full_name": "NIDHI SHARMA", "dob": "1995-08-10", "gender": "Female", "total_income": "40000", "occupation": "Designer", "age": "29" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "7778889990" } ], "address_info": [ { "address": "22, CREATIVE HUB, MUMBAI", "state": "MH", "type": "Owns,Permanent", "postal": "400001", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "NIDHI.S@DESIGN.COM" } ], "identity_info": { "pan_number": [ { "id_number": "CDEFG1234H" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "CDEFG1234H", "full_name": "NIDHI SHARMA", "full_name_split": [ "NIDHI", "SHARMA" ], "masked_aadhaar": "XXXXXXXX1234", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "F", "dob": "1995-08-10", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample08", "mobile_number": "9123456789", "prefill_details": { "client_id": "prefill_report_v2_Sample08", "name": "VIVEK JAIN", "mobile": "9123456789", "personal_info": { "full_name": "VIVEK JAIN", "dob": "1983-04-18", "gender": "Male", "total_income": "90000", "occupation": "Architect", "age": "42" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "9123456789" } ], "address_info": [ { "address": "50, DESIGN STREET, PUNE", "state": "MH", "type": "Owns,Permanent", "postal": "411001", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "VIVEK.J@ARCH.IN" } ], "identity_info": { "pan_number": [ { "id_number": "IJKLM4567N" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "IJKLM4567N", "full_name": "VIVEK JAIN", "full_name_split": [ "VIVEK", "JAIN" ], "masked_aadhaar": "XXXXXXXX4567", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "M", "dob": "1983-04-18", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample09", "mobile_number": "8234567890", "prefill_details": { "client_id": "prefill_report_v2_Sample09", "name": "POOJA SINGH", "mobile": "8234567890", "personal_info": { "full_name": "POOJA SINGH", "dob": "1991-06-01", "gender": "Female", "total_income": "50000", "occupation": "Marketing Manager", "age": "34" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "8234567890" } ], "address_info": [ { "address": "65, ROYAL COMPLEX, JAIPUR", "state": "RJ", "type": "Owns,Permanent", "postal": "302001", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "POOJA.S@MARKET.COM" } ], "identity_info": { "pan_number": [ { "id_number": "NOPQR5678S" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "NOPQR5678S", "full_name": "POOJA SINGH", "full_name_split": [ "POOJA", "SINGH" ], "masked_aadhaar": "XXXXXXXX5678", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "F", "dob": "1991-06-01", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" },
    { "data": { "client_id": "mobile_to_prefill_v3_Sample10", "mobile_number": "9765432101", "prefill_details": { "client_id": "prefill_report_v2_Sample10", "name": "SANJAY VERMA", "mobile": "9765432101", "personal_info": { "full_name": "SANJAY VERMA", "dob": "1978-02-28", "gender": "Male", "total_income": "75000", "occupation": "Accountant", "age": "47" }, "phone_info": [ { "reported_date": "2025-02-01", "type_code": "H", "number": "9765432101" } ], "address_info": [ { "address": "8, FINANCE AVENUE, KOLKATA", "state": "WB", "type": "Owns,Permanent", "postal": "700001", "reported_date": "2025-02-01" } ], "email_info": [ { "reported_date": "2024-12-01", "email_address": "SANJAY.V@FINANCE.COM" } ], "identity_info": { "pan_number": [ { "id_number": "TUVWX9012Y" } ], "passport_number": [], "driving_license": [], "voter_id": [], "aadhaar_number": [ { "id_number": "XXXXXXXXXXXX" } ], "ration_card": [], "other_id": [] } }, "pan_details": { "pan_status": "success", "pan_details": { "pan_number": "TUVWX9012Y", "full_name": "SANJAY VERMA", "full_name_split": [ "SANJAY", "VERMA" ], "masked_aadhaar": "XXXXXXXX9012", "address": { "line_1": "", "line_2": "", "street_name": "", "zip": "", "city": "", "state": "", "country": "", "full": "" }, "email": None, "phone_number": None, "gender": "M", "dob": "1978-02-28", "input_dob": None, "aadhaar_linked": True, "dob_verified": False, "dob_check": False, "category": "person", "status": "valid", "less_info": False } }, "status": "success" }, "status_code": 200, "success": True, "message": "Success", "message_code": "success" }
]

@app.route('/')
def index():
    """Renders the frontend HTML page."""
    return render_template('index.html')


@app.route('/api/verify', methods=['POST'])
def verify_user():
    """
    Verifies user details against the mock database.
    Expects a JSON payload with 'name' and 'mobile'.
    """
    data = request.get_json()
    if not data or 'name' not in data or 'mobile' not in data:
        return jsonify({"success": False, "message": "Invalid input. 'name' and 'mobile' are required."}), 400

    name = data.get('name', '').strip().upper()
    mobile = data.get('mobile', '').strip()

    # Find the user in our mock database
    for entry in mock_api_database:
        if (entry['data']['prefill_details']['name'].upper() == name and
            entry['data']['mobile_number'] == mobile):
            return jsonify(entry)

    # If no user is found
    return jsonify({"success": False, "message": "User not found."}), 404


# This allows you to run the app directly using "python app.py"
if __name__ == '__main__':
    app.run(debug=True, port=5001)